name: notanerd_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.6 # Add this line
  google_sign_in_mocks: ^0.3.0 # Add this lin
  flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true