name: notanerd_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #firebase_ui_auth: ^3.0.0
  #firebase_ui_oauth_google: ^2.0.0
  cupertino_icons: ^1.0.8
  firebase_ui_auth: ^3.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_ui_oauth_google: ^2.0.0
  google_sign_in: ^6.3.0
  #firebase_auth: ^6.0.0
  #google_sign_in: ^7.1.1
  #firebase_core: ^4.0.0
  #cloud_firestore: ^6.0.0
  #firebase_ui_oauth_google: ^2.0.0
  #google_sign_in: ^6.3.0
  #firebase_ui_oauth_google: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  build_runner: ^2.6.1
  google_sign_in_mocks: ^0.3.0
  #google_sign_in_mocks: ^0.3.0
  #flutterfire_cli: ^1.3.1

flutter:
  uses-material-design: true