// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const String webClientId = '203173142718-6nrg5mdjr10hbgpvtc0t97iaenuqt5bf.apps.googleusercontent.com';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsxsJKGhaVgmj8srSQIkNe4VpQBiLQ8ME',
    appId: '1:239633005577:web:134dd4881168eede454cd8',
    messagingSenderId: '239633005577',
    projectId: 'notanerd-c17a2',
    authDomain: 'notanerd-c17a2.firebaseapp.com',
    storageBucket: 'notanerd-c17a2.firebasestorage.app',
    measurementId: 'G-RB5S13F05J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrOt8BFc5olla9yUe4Z4ySAC2OMxcwUE',
    appId: '1:239633005577:android:e64c9fcbadfc5f5f454cd8',
    messagingSenderId: '239633005577',
    projectId: 'notanerd-c17a2',
    storageBucket: 'notanerd-c17a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu9Xl3xA4Hgx-8cZ0TT52i8D7g_pif9bo',
    appId: '1:239633005577:ios:c8f404685cbeaf1c454cd8',
    messagingSenderId: '239633005577',
    projectId: 'notanerd-c17a2',
    storageBucket: 'notanerd-c17a2.firebasestorage.app',
    androidClientId: '239633005577-1eii94if6i1hdncudb6tofl9b7g7ru2a.apps.googleusercontent.com',
    iosClientId: '239633005577-0bri5iqsu1f9kb3e8c8oks7mapkkh5d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}