# .github/workflows/frontend-ci.yml

name: Flutter Frontend CI

on:
  push:
    branches:
      - main
    paths:
      # This ensures the workflow only runs when changes are made in the frontend directory.
      - 'frontend/**'
  # This allows you to run the workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        # This action sets up the Flutter environment for us.
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.x'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Check code formatting
        run: |
          flutter format --dry-run --set-exit-if-changed .

      - name: Analyze code
        run: |
          flutter analyze

      - name: Run widget tests
        run: |
          flutter test
